name: dio_evm_e2e_test
description: x402 Client Dio EVM e2e test
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dio: ^5.9.1
  dotenv: ^4.2.0
  x402:
  x402_dio:

dev_dependencies:
  test: ^1.29.0
