name: dart_client_shelf_e2e_tests
description: Dart Client + x402 Shelf Server EVM E2E Tests
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dotenv: ^4.2.0
  shelf: ^1.4.2
  x402:
  x402_shelf:

dev_dependencies:
  test: ^1.30.0
