name: shelf_evm_denied_e2e_test
description: x402 Shelf Server + Client Wrapper EVM Denied e2e test
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dotenv: ^4.2.0
  shelf: ^1.4.2
  x402:
  x402_shelf:

dev_dependencies:
  test: ^1.29.0
