name: e2e_tests
description: E2E tests (Dart client + TS server, Dart client + Dart server, TS client + Dart server)
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dio: ^5.10.0
  dotenv: ^4.2.0
  http: ^1.6.0
  shelf: ^1.4.2
  x402:
  x402_dio:
  x402_shelf:

dev_dependencies:
  test: ^1.31.1
