name: server_shelf_example
description: x402 Shelf Server Example
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dotenv: ^4.2.0
  shelf: ^1.4.2
  x402:
  x402_shelf:

dev_dependencies:
  lint: ^2.8.0
