name: ts_client_shelf_evm_e2e_test
description: TS Client + x402 Shelf Server EVM e2e test
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dotenv: ^4.2.0
  shelf: ^1.4.2
  x402:
  x402_shelf:

dev_dependencies:
  test: ^1.29.0
