name: Build x402 image

on:
    workflow_dispatch:
    push:
        paths:
            - e2e/Dockerfile

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: docker/setup-buildx-action@v3

            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/cache@v5
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-x402
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Build & push
              run: |
                  docker buildx build \
                    --cache-from=type=local,src=/tmp/.buildx-cache \
                    --cache-to=type=local,dest=/tmp/.buildx-cache-new \
                    -t ghcr.io/minhqdao/x402:${{ github.sha }} \
                    -t ghcr.io/minhqdao/x402:latest \
                    --push \
                    e2e

            - name: Update cache
              if: always()
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
