name: CI
on: push

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - uses: bluefireteam/melos-action@v3
            - run: melos format --set-exit-if-changed
    analyze:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - uses: bluefireteam/melos-action@v3
            - run: melos analyze
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - uses: bluefireteam/melos-action@v3
            - run: melos test
    e2e:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - uses: actions/setup-node@v6

            - name: Run e2e tests
              working-directory: e2e
              env:
                  EVM_PRIVATE_KEY: ${{ secrets.EVM_PRIVATE_KEY }}
                  SVM_PRIVATE_KEY: ${{ secrets.SVM_PRIVATE_KEY }}
                  EVM_ADDRESS: ${{ secrets.EVM_ADDRESS }}
                  SVM_ADDRESS: ${{ secrets.SVM_ADDRESS }}
                  EVM_PRIVATE_KEY_PAYER: ${{ secrets.EVM_PRIVATE_KEY_PAYER }}
                  SVM_PRIVATE_KEY_PAYER: ${{ secrets.SVM_PRIVATE_KEY_PAYER }}
              run: |
                  npm install
                  dart test --concurrency=1 .
